-- DROP TABLE IF EXISTS Workouts;

CREATE TABLE Users (
  Id SERIAL PRIMARY KEY,
  UserName VARCHAR(255) NOT NULL,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Pword VARCHAR(255)
)