CREATE TABLE Workouts (
  Id SERIAL PRIMARY KEY,
  Program VARCHAR(255) NOT NULL,
  AvgMinutes VARCHAR(255),
  Trainer VARCHAR(255) NOT NULL,
  WorkoutType VARCHAR(255) NOT NULL,
  NumberOfWorkouts VARCHAR(255)
);

CREATE TABLE Users (
  Id SERIAL PRIMARY KEY,
  UserName VARCHAR(255) NOT NULL,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Pword VARCHAR(255)
);